### PR TITLE
Update Kibana to v4.1.1

### PR DESCRIPTION
**Pull request by delfuego**
Simple pull request, to update Kibana to the current release (v4.1.1).

### CODE REVIEW

**Comment by berglh** [comment]
+1, but should update the README to reflect the version change as well delfuego :)

**Comment by marcbachmann** [comment]
Thanks. Yes, that was the reason why I didn't merged this when I received the pr. Sorry for ignoring that.
I'm very busy.

**Comment by marcbachmann** [comment]
It's building :wink:

**Comment by berglh** [comment]
Thanks :+1:

**Comment by delfuego** [comment]
Sweet -- sorry about forgetting the readme, and thanks!

**Pull request merged**
